# Generated by Django 4.2 on 2023-04-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('height', models.FloatField()),
                ('mass', models.FloatField()),
                ('model', models.TextField(blank=True)),
                ('mark', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('engine_type', models.CharField(choices=[('INLINE', 'Inline'), ('V Engine', 'V Engine'), ('VR Engine', 'VR Engine'), ('W Engine', 'W Engine')], default='INLINE')),
            ],
        ),
    ]
